---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
# bloom #

Scaling, counting Bloom filter for R using Rcpp bindings for
[dablooms](https://github.com/bitly/dablooms/).

Note the dablooms implementation requires an additional metadata id for
insertions and deletions.  This id is a monotonically increasing integer which
is used to determine which scaling filter the item should be added or removed
from.

### Example usage

```{r}
library(bloom)
bloom <- bloom(capacity = 1000, error_rate = .05, filename = "/tmp/bloom.bin")
bloom$add("foo", 2)
bloom$contains("bar")
bloom$contains("foo")
bloom$remove("foo", 2)
bloom$contains("foo")
bloom$add("foo", 2)
rm(bloom)
bloom <- bloom(capacity = 1000, error_rate = .05, filename = "/tmp/bloom.bin", exists = TRUE)
bloom$contains("foo")
```


Or use the new wraparound functions:


```{r}
library(bloom)
bloomf<-bloom_create(capacity=2000, error_rate=0.05, filename='/tmp/bloom.bin')
t<-unlist(strsplit('this is a test',' '))
bloom_add(bloomf, t)
bloom_contains(bloomf,t)
bloom_remove(bloomf,'this',1)
bloom_contains(bloomf, t)
```


